services:
  app:
    build: .
    container_name: fabric-app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./app:/app/app


