services:
  app:
    build: .
    container_name: fabric-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      COBALT_BASE_URL: http://cobalt-api:9000


networks:
  cobalt-network:
    external: true