services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    container_name: cobalt-api
    init: true
    read_only: true
    restart: unless-stopped
    network_mode: "host"
    # Открываем порт 9000 для доступа извне:
    ports:
      -  "9000:9000"
    environment:
        API_URL: "http://cobalt-api:9000"

    labels:
      - com.centurylinklabs.watchtower.scope=cobalt
    volumes:
      - ./cookies.json:/app/cookies.json  # Если нужна поддержка cookies

  # Watchtower автоматически обновляет образ cobalt
  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900 --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # # Пример: генератор visitor_data для YouTube (может не понадобиться)
  # yt-session-generator:
  #   image: ghcr.io/imputnet/yt-session-generator:webserver
  #   container_name: yt-session-generator
  #   init: true
  #   restart: unless-stopped
  #   labels:
  #     - com.centurylinklabs.watchtower.scope=cobalt
